### ISSUE TITLE
Wall Lantern breaks MineColonies schematic preview

### ISSUE THREAD

**Issue by AnyankaT** [MehVahdJukaar/amendments#104]
I've used Amendments wall lanterns in my MineColonies custom style, and a recent update has broken compatibility between these two mods. If a wall lantern is in a build, I can scan it with the MineColonies/Structurize scan tool, but I get an unrecoverable error when I try to place the build in the world. I've also had many people who use the style pack contact me and/or MineColonies about the same issue. It appears to be a change in Moonlight Lib that has caused this.

MineCraft 1.20.1
MineColonies 1.20.1-1.1.601-BETA
Structurize 1.20.1-1.0.738-BETA
Embeddium 0.3.23+mc1.20.1
Amendments 1.20.1 1.2.8
Moonilght Library 1.20-2.12.6
[latest.log](https://github.com/user-attachments/files/16234772/latest.log)

**Comment by MehVahdJukaar** [comment]
That log is huge, don't see a crash at the end and I don't know what I should look for nor how mineconies work. Wall lanterns are just a normal tile entities so shouldn't this be an issue of that mod?

**Comment by AnyankaT** [comment]
I've included the relevant excerpt from the log. The client didn't crash, but the blueprint was unusable. I've already reported this to MineColonies, but they said it's an issue with Moonlight Lib, so I'm now coming to you.

[excerpt.txt](https://github.com/user-attachments/files/16235063/excerpt.txt)

**Comment by MehVahdJukaar** [comment]
Does it work without enbeddium?

**Comment by AnyankaT** [comment]
Same thing happens with Embeddium turned off.
[latest.log](https://github.com/user-attachments/files/16235357/latest.log)

**Comment by MehVahdJukaar** [comment]
Hm i don't see it crashing there tho unlike last log

**Comment by AnyankaT** [comment]
Sorry, I pasted the wrong file. Too many "latest.log" files floating around....

[next excerpt.txt](https://github.com/user-attachments/files/16235448/next.excerpt.txt)

**Comment by AnyankaT** [comment]
If it helps to narrow things down, I also noticed a couple months ago that the same thing happens with the ceiling banners - although I didn't use them in the style pack, so I didn't report it.

**Comment by Yorunina** [comment]
Meeting same issue with higher version minecolonies and amendments. Many player crashed because using old english stylePack when preview level 5 townhall blueprint.
```
Thread: Render thread
Suspected Mods: 
	Embeddium (embeddium), Version: 0.3.30+mc1.20.1
		Mixin class: me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin
		Target: net.minecraft.client.renderer.LevelRenderer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:15709)

	Moonlight Library (moonlight), Version: 1.20-2.12.11
		Issue tracker URL: https://github.com/MehVahdJukaar/Moonlight/issues
		at TRANSFORMER/moonlight@1.20-2.12.11/net.mehvahdjukaar.moonlight.api.block.DynamicRenderedBlockTile.shouldRenderFancy(DynamicRenderedBlockTile.java:59)

	Structurize (structurize), Version: 1.20.1-1.0.742-RELEASE
		Issue tracker URL: https://github.com/ldtteam/structurize/issues/new/choose
		at TRANSFORMER/structurize@1.20.1-1.0.742-RELEASE/com.ldtteam.structurize.client.BlueprintRenderer.drawUnsafe(BlueprintRenderer.java:442)

	Amendments (amendments), Version: 1.20-1.2.8
		Issue tracker URL: https://github.com/MehVahdJukaar/amendments/issues
		at TRANSFORMER/amendments@1.20-1.2.8/net.mehvahdjukaar.amendments.common.tile.SwayingBlockTile.onFancyChanged(SwayingBlockTile.java:31)

	MineColonies (minecolonies), Version: 1.20.1-1.1.605-BETA
		Issue tracker URL: https://github.com/ldtteam/minecolonies/issues/new/choose
		at TRANSFORMER/minecolonies@1.20.1-1.1.605-BETA/com.minecolonies.core.client.render.worldevent.ColonyBlueprintRenderer.renderBlueprints(ColonyBlueprintRenderer.java:172)
Stacktrace:
	at net.mehvahdjukaar.amendments.common.tile.SwayingBlockTile.onFancyChanged(SwayingBlockTile.java:31) ~[amendments-1.20-1.2.8.jar%23356!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.block.DynamicRenderedBlockTile.shouldRenderFancy(DynamicRenderedBlockTile.java:59) ~[moonlight-1.20-2.12.11-forge.jar%23450!/:?] {re:classloading}
	at net.mehvahdjukaar.amendments.client.renderers.WallLanternBlockTileRenderer.shouldRender(WallLanternBlockTileRenderer.java:52) ~[amendments-1.20-1.2.8.jar%23356!/:?] {re:classloading}
	at net.mehvahdjukaar.amendments.client.renderers.WallLanternBlockTileRenderer.m_142756_(WallLanternBlockTileRenderer.java:43) ~[amendments-1.20-1.2.8.jar%23356!/:?] {re:classloading}
	at com.ldtteam.structurize.client.BlueprintRenderer.drawUnsafe(BlueprintRenderer.java:442) ~[structurize-1.20.1-1.0.742-RELEASE.jar%23494!/:1.20.1-1.0.742-RELEASE] {re:classloading}
```
Showing SwayingblockTile may cause this, but i have no idea about how digging into deep.

**Comment by Yorunina** [comment]
com.ldtteam.structurize.client.BlueprintRenderer.drawUnsafe(BlueprintRenderer.java:442)
```java
        // Block entities
        mc.getProfiler().popPush("struct_render_blockentities");
        for (final BlockEntity tileEntity : tileEntities)
        {
            final BlockEntityRenderer<BlockEntity> renderer = mc.getBlockEntityRenderDispatcher().getRenderer(tileEntity);
            // line 442 below, using should render method, which related to WallLanternBlockTileRenderer.shouldRender
            if (renderer == null || !renderer.shouldRender(tileEntity, ourCamera.getPosition()))
            {
                continue;
            }
```

**Comment by MehVahdJukaar** [comment]
I need latest.log

**Comment by Yorunina** [comment]
> I need latest.log

[latest.log](https://github.com/user-attachments/files/16783989/latest.log)

**Comment by AnyankaT** [comment]
I have new information on this issue, and I've also reported the problem on the MineColonies Discord: https://discord.com/channels/139070364159311872/724810039281451028/1279081089897463860

I received an "Unrecoverable error occurred during rendering blueprint ..." and the latest.log indicates that it's the swaying wall lanterns. I've updated the relevant mods to their most recent versionsin the process of updating the modpack, running on the test server for our community.: 

- Structurize 755 
- MineColonies 647 
- Amendments 1.2.8
- MoonlightLib 2.12.17
[latest.log](https://github.com/user-attachments/files/16818325/latest.log)

**Comment by MehVahdJukaar** [comment]
try using newest version

**Comment by AnyankaT** [comment]
I can confirm that the latest version does not cause structurize to break! Unfortunately, I've already removed both Amendments and Supplementaries from my style pack, because the nearly 1,000 people who have downloaded the style pack - dozens of whom have complained to me or in the Minecolonies discord - could't wait nearly two months for a fix.

I still love the mod, and will use it in my server modpack, but since Structurize is so touchy, I'm safer not including this or any third-party mods (outside the Minecolonies dependencies) in my style.

**Comment by AnyankaT** [comment]
Thanks for this!
