### ISSUE TITLE
1.20.1 crashing game when attempting to place a torch

### ISSUE THREAD

**Issue by NOTV0ID** [MehVahdJukaar/amendments#106]
When I have the amendments mod installed, it causes my forge .1.20.1 modded world to crash completely, not just the the main menu. This happens every single time without fail and only occurs when this mod is installed. 

I don't know what information is needed for this but I can try to provide anything in order to fix this because I love this mod and don't want to just remove it if possible.

**Comment by MehVahdJukaar** [comment]
Update your mods and send latest.log

**Comment by shaohenglim2** [comment]
@MehVahdJukaar I have a similar situation here where the game crashes when I have a torch in my hand. Here's what I had ChatGPT analyze, with my Crash Report attached. 
https://chatgpt.com/share/17294b47-0e0c-4e6c-bd65-e0efdddc90d3
[crash-2024-08-10_11.36.11-client.txt](https://github.com/user-attachments/files/16568371/crash-2024-08-10_11.36.11-client.txt)

**Comment by shaohenglim2** [comment]
> @MehVahdJukaar I have a similar situation here where the game crashes when I have a torch in my hand. Here's what I had ChatGPT analyze, with my Crash Report attached. 
> https://chatgpt.com/share/17294b47-0e0c-4e6c-bd65-e0efdddc90d3
> [crash-2024-08-10_11.36.11-client.txt](https://github.com/user-attachments/files/16568371/crash-2024-08-10_11.36.11-client.txt)
> 
> 
I'm setting "Torch Item Holding" to False for now, so I'll play with it for a while and see if I have any problems.

**Comment by MehVahdJukaar** [comment]
Same issue same answer. Your mods are outdated
