### ISSUE TITLE
[Feature Request] Ability to scale torches in hand as you can with lanterns

### ISSUE THREAD

**Issue by 3ncanis** [MehVahdJukaar/amendments#110]
When using First Person Model the torch is very large, would love to be able to scale it in the same way you can lanterns.

![Jdk-17_Screenshot_2024 08 08_-_19 31 37 87](https://github.com/user-attachments/assets/88345b37-1616-479a-b271-4d3efe002361)
![Jdk-17_Screenshot_2024 08 08_-_19 34 33 36](https://github.com/user-attachments/assets/40004431-547c-4309-a19c-eca70dfadeb8)

**Comment by MehVahdJukaar** [comment]
added
