### ISSUE TITLE
GUI of Podium With A Book  Not Working on Server 1.20.1

### ISSUE THREAD

**Issue by NKanoya** [MehVahdJukaar/amendments#116]
**Minecraft 1.20.1**  
**Moonlight 2.12.11**  
**Amendments 1.2.8** 
**Server Arclight 1.20.1** 

On server, there were no responses when clicking on the podium. No GUI or Inventory opened. That made it impossible to turn pages or edit it.
I tested it in a singleplayer game, but it turned out to work fine. The GUI showed with the figures of ink and quill. 
And I noticed on server whenever a player clicks on the podium, there will be some infomation shown in the console, which mention the mod name 'moonlight'. I posted the issue here since amendments adds features to podium.
Fortunately, this bug didn't lead to any crashes by far.

16.08 19:04:43 [Server] ERROR Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@68ecac7b, suppressing error
16.08 19:04:43 [Server] INFO java.lang.NullPointerException: Cannot read field "f_35978_" because "this.playerInventory" is null
16.08 19:04:43 [Server] INFO at net.minecraft.world.inventory.LecternMenu.getBukkitView(LecternContainerMixin.java:570) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.world.inventory.LecternMenu.getBukkitView(LecternContainerMixin.java:522) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.world.inventory.AbstractContainerMenu.bridge$getBukkitView(AbstractContainerMenuMixin.java:1254) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.world.inventory.AbstractContainerMenu.transferTo(AbstractContainerMenuMixin.java:949) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1306) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23187!/:arclight-1.20.1-1.0.4-fd335c1]
16.08 19:04:43 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1296) ~[arclight-1.20.1-1.0.4-fd335c1.jar%23187!/:arclight-1.20.1-1.0.4-fd335c1]
16.08 19:04:43 [Server] INFO at net.minecraftforge.network.NetworkHooks.handler$ccc000$arclight$openContainer(NetworkHooksMixin.java:533) ~[forge-1.20.1-47.2.20-universal.jar%23218!/:?]
16.08 19:04:43 [Server] INFO at net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooksMixin.java:207) ~[forge-1.20.1-47.2.20-universal.jar%23218!/:?]
16.08 19:04:43 [Server] INFO at net.mehvahdjukaar.moonlight.api.platform.forge.PlatHelperImpl.openCustomMenu(PlatHelperImpl.java:197) ~[moonlight-1.20-2.12.11-forge.jar%23199!/:?]
16.08 19:04:43 [Server] INFO at net.mehvahdjukaar.moonlight.api.platform.PlatHelper.openCustomMenu(PlatHelper.java) ~[moonlight-1.20-2.12.11-forge.jar%23199!/:?]
16.08 19:04:43 [Server] INFO at net.mehvahdjukaar.moonlight.api.platform.PlatHelper.openCustomMenu(PlatHelper.java:304) ~[moonlight-1.20-2.12.11-forge.jar%23199!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.world.level.block.LecternBlock.handler$zch000$openCustomMenu(LecternBlockMixin.java:1027) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.world.level.block.LecternBlock.m_54484_(LecternBlockMixin.java) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.world.level.block.LecternBlock.m_6227_(LecternBlockMixin.java:275) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour_BlockStateBaseMixin.java:778) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameModeMixin.java:846) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerPlayNetHandlerMixin.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(CPlayerTryUseItemOnBlockPacketMixin.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(CPlayerTryUseItemOnBlockPacketMixin.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.network.protocol.PacketUtils.md6f9a26$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]
16.08 19:04:43 [Server] INFO at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23213!/:?]

**Comment by MehVahdJukaar** [comment]
Don't use hybrid servers.this is an issue of bukkit mods. Hybrid servers are not supported by anyone in the modding community, first and foremost forge itself
