### ISSUE TITLE
Wall Lantern collision causes crash

### ISSUE THREAD

**Issue by NilsIgris** [MehVahdJukaar/amendments#120]
Hello, 
We updated this evening Amendments and Moonlight lib to their latest version :
- Amendments (amendments), Version: 1.20-1.2.9
- Moonlight Library (moonlight), Version: 1.20-2.12.17

And suddenly the server crashed with this report log that states a colision between a bee and a wall lantern block causes it to crash.
(idk some kind of pacific rim for antman maybe ?)

[crash-2024-09-04_20.38.41-server.txt](https://github.com/user-attachments/files/16875502/crash-2024-09-04_20.38.41-server.txt)

If you have any idea where it's from amendments or moonlight lib let me know, thanks for helping

**Comment by MehVahdJukaar** [comment]
are you sure you updated it on both server and client?

**Comment by goofygoober-17** [comment]
> are you sure you updated it on both server and client?

Awesome mod ive been loving forever! I also had this problem today and it crashed both server and client and both were updated. Looks like any entity like the player collides and crashes

**Comment by Feyreth** [comment]
I can also confirm this happening on my own server after updating both client and server profiles. Seems to also be happening with hanging signs. I provided server logs in the Supplementaries discord server because their was no crashlog from Minecraft.

**Comment by NilsIgris** [comment]
Yes it was updated on both server and clients
We had to revert the update to the last version

**Comment by MehVahdJukaar** [comment]
fixed
