### ISSUE TITLE
Item Torch Size not changing when First Person Model is installed/Can't disable Torch Item Holding with First Person Model

### ISSUE THREAD

**Issue by 3ncanis** [MehVahdJukaar/amendments#125]
The size of the torch stays the same no matter how small you set the value to with First Person Model. You also cannot disable the amendments feature when using First Person Model.

Edit: I just realized this feature is completely handled by First Person Model and its requirement, Not Enough Animations. So just a fix for disabling the amendments feature would be needed.

**Comment by MehVahdJukaar** [comment]
Config only affects the size of the first person model. If a mod were to alter how that is rendered then it won't work. There's a config to disable the feature

**Comment by 3ncanis** [comment]
The disable option doesn't seem to be working for me

**Comment by MehVahdJukaar** [comment]
And did you reboot the game?

**Comment by 3ncanis** [comment]
Yeah, tried on a clean instance with just First Person Model, Not Enough Animations, and Amendments too, still giant torch unfortunately.

**Comment by MehVahdJukaar** [comment]
Can you turn that off when that mod isn't on?

**Comment by 3ncanis** [comment]
With just amendments and moonlight lib i'm able to turn it off successfully yeah

**Comment by 3ncanis** [comment]
Okay I have no idea what happened but now settings torch_item_holding = false in the .toml file works! I don't know if its different because I changed it directly in the config file manually instead of a mod menu config mod or what but it works now, sorry for the confusion.
