### ISSUE TITLE
Lanterns causing Internal server error

### ISSUE THREAD

**Issue by JawnWick88** [MehVahdJukaar/amendments#129]
When you bump into a hanging lantern on the wall it kicks you out the game and says internal server error

**Comment by MehVahdJukaar** [comment]
I Need latest.log

**Comment by JawnWick88** [comment]
[latest.log](https://github.com/user-attachments/files/16988142/latest.log)

**Comment by MehVahdJukaar** [comment]
you are not using the mod latest version

**Comment by JawnWick88** [comment]
will update it and double check thanks

**Comment by mothfuzz** [comment]
same issue being reported at https://github.com/MehVahdJukaar/amendments/issues/131
