### ISSUE TITLE
Wall Lantern model messed up

### ISSUE THREAD

**Issue by Daimon6453** [MehVahdJukaar/amendments#13]
The model for the wall lanterns seems to be glitched - the lantern has physics but it also doesn't. There's like two lanterns - one with physics, one without. I tested with and without shaders; they were not the issue.

**Comment by MehVahdJukaar** [comment]
is your config for fast lanterns on or off?

**Comment by MehVahdJukaar** [comment]
does this happen with just the mod on?

**Comment by Daimon6453** [comment]
I have not tested it alone, no. Also, where is the fast lanterns config setting? Is it in base minecraft 1.20.1? Or is it in one of my other mods like sodium or iris?

**Comment by Vaskritaya** [comment]
Can confirm this occurs in an instance of the game exclusively using amendments and moonlightlib. 
An example image, after knocking into the lantern a bit to make the problem more visible:
![image](https://github.com/MehVahdJukaar/amendments/assets/22992007/e542d484-9782-4ce2-b709-b4da4a5a2a86)

With fast lanterns on, the lantern appears as one would expect.

![image](https://github.com/MehVahdJukaar/amendments/assets/22992007/49fb1331-ff8f-44ac-a7b9-0bc1eb8a11c1)

**Comment by Vaskritaya** [comment]
This appears to be resolved in the latest versions of the mod.
