### ISSUE TITLE
NeoForge 1.21.1 Invisible Textures when Amendments is Active.

### ISSUE THREAD

**Issue by Zelioth** [MehVahdJukaar/amendments#132]
Minecraft 1.21.1
Neoforge 21.1.55
Amendments 1.2.10

When Amendments is active some textures fail to render. Cauldrens with water in them, Lootr Chests (Not an issue with Lootr barrels from what I can test) and sophicated backpacks (Not an issue with sophicated from what I can tell) 
![2024-09-19_13 12 46](https://github.com/user-attachments/assets/5b9dabb0-634d-46bf-9dc0-2dca0d1112c3)

Confirmed that it is Amendments by disabling every mod and testing them being enabled in groups. This may be a compat issue but I couldn't find another mod that changed this when Amendments was active. 

[latest.log](https://github.com/user-attachments/files/17064089/latest.log)
[debug.log](https://github.com/user-attachments/files/17064091/debug.log)

**Comment by MehVahdJukaar** [comment]
Do you have a texture pack? Also what about rendering mods? Try with amendments alone plus maybe those mods. If it works there not my issue

**Comment by Zelioth** [comment]
No Texture or Resource packs, The only thing we have added is Embeddium and in my client alone Sodium. It does it with both. The Published pack is called "Friends United 2.1" and it does it in our latest version. With or without Sodium, Embeddium.

**Comment by Zelioth** [comment]
It must be a conflict with another mod. I did verify just amendments works with basic neoforge but I can't seem to find the conflicting mod. It's not a render related mod such as sodium or embeddium

**Comment by Zelioth** [comment]
The issue is Just Utilities. I have reported it. I apologize for the issue error.
