### ISSUE TITLE
Amendments Lectern/Book and Quill not saving text or saving book properly

### ISSUE THREAD

**Issue by twenty41** [MehVahdJukaar/amendments#133]
For me the lectern UI doesn't save text or let you sign / complete the book properly

[Video showing problem here](https://github.com/user-attachments/assets/80f77663-cf5b-4325-b891-8ca84255f67b)

You can see around 0:30 I kind of got it to save the text content but only after making a 2nd page, then I couldn't even replicate that.

**Comment by MehVahdJukaar** [comment]
version?

**Comment by MehVahdJukaar** [comment]
fixed in new version

**Comment by twenty41** [comment]
sorry would've answered didn't see
