### ISSUE TITLE
Crash when placing ceiling banners

### ISSUE THREAD

**Issue by ParanormalChicken** [MehVahdJukaar/amendments#137]
The only mods installed are Amendments, Moonlight Library, and QSL/QFAPI.
Minecraft version 1.21.1, Quilt version 0.26.4
`java.lang.IllegalStateException: Invalid block entity amendments:ceiling_banner // net.mehvahdjukaar.amendments.common.tile.CeilingBannerBlockTile state at class_2338{x=78, y=72, z=-95}, got Block{amendments:ceiling_banner_white}[attached=false,facing=west]`
https://mclo.gs/DOEWUyp

**Comment by ParanormalChicken** [comment]
Using the /setblock command, the console logs an error when executing the command, but upon updating the blocks, it kicks you out of the client server with [this error log](https://mclo.gs/r8hitWY)
Upon rejoining, the banner is placed, but it does not render. Breaking a banner and interacting with the world results in [a similar error log](https://mclo.gs/auPNA62).
Using the middle mouse button on the banner [crashes the game](https://mclo.gs/cLdyZ0a)
The game still [crashes](https://mclo.gs/qpmSROK) when placing manually, even in the new update

**Comment by ParanormalChicken** [comment]
It appears this is not exclusive to Quilt, Fabric has the same issue.

**Comment by MehVahdJukaar** [comment]
Fabric moment. This is due to vanilla bug, patched by forge. Fabric of course didn't I give a damn lol

**Comment by MehVahdJukaar** [comment]
I'll release a fix soon

**Comment by ParanormalChicken** [comment]
It seems to have been fixed, as far as I can tell
