### ISSUE TITLE
[Neoforge] Cauldron dyed water always giving red no matter the color inside.

### ISSUE THREAD

**Issue by Serook-Arzzal** [MehVahdJukaar/amendments#139]
Tested on : Neoforge 21.1.68
Amendment version : 1.21-1.2.12 (also tested on 1.2.17)

Tested with only amendment active (and moonlight lib).

No matter what type of dye is use in a cauldron full of water, every items that can be dyed and every glass bottle i use to put the water in, it's giving me red dye.

![Capture d'écran 2024-10-12 131420](https://github.com/user-attachments/assets/f553602b-ae5b-40a5-b356-ad15453a8aa9)
![Capture d'écran 2024-10-12 131458](https://github.com/user-attachments/assets/80d6c7ab-fa0b-452d-a56c-4f85f7324374)
![Capture d'écran 2024-10-12 131535](https://github.com/user-attachments/assets/77f5b503-029e-4698-8290-290312060336)
![Capture d'écran 2024-10-12 131547](https://github.com/user-attachments/assets/3008daf1-463e-4d60-b964-95751a0ba28b)

**Comment by MehVahdJukaar** [comment]
fixed
