### ISSUE TITLE
Crash on placing Candle atop skulls on server

### ISSUE THREAD

**Issue by oitsjustjose** [MehVahdJukaar/amendments#14]
# Versions:

- NeoForge: 47.1.100
- Amendments: 1.20-1.0.8
- Supplementaries (if it matters): 1.20-2.8.1
- Moonlight: 1.20-2.10.0

# [Crash Report](https://gist.github.com/oitsjustjose/ea956a709acf9c22df38d79643b6886c)

# Details

Placed an un-dyed candle atop two skeleton skulls and my dedicated server crashed.

**Comment by mxnmnm** [comment]
this seems to have been fixed
