### ISSUE TITLE
Normal haning sign tweaks don't work

### ISSUE THREAD

**Issue by Hippopipo** [MehVahdJukaar/amendments#146]
![kuva](https://github.com/user-attachments/assets/af627d41-3a50-42d0-ae84-7d43bf398975)
![kuva](https://github.com/user-attachments/assets/580a2aa9-7e53-4b90-8601-28da71a881ec)
latest.log: https://mclo.gs/DWhY6Nc
Probably a mod compat issue.
Also the normal sign hitbox tweak works, and you can hear the swinging effect, but the visuals don't change.

**Comment by MehVahdJukaar** [comment]
yes it indeed is. You MUST have intalled a mod that specifically alters hanging signs

**Comment by AlwaysReadyWBY** [comment]
If you have Enhanced Block Entities installed, turn all its sign related features off and set force resourcepack compat to true. That fixes the problem for me.

**Comment by AlwaysReadyWBY** [comment]
If you have Enhanced Block Entities installed, turn all its sign related features off and set force resourcepack compat to true. That fixes the problem for me.

**Comment by Hippopipo** [comment]
> If you have Enhanced Block Entities installed, turn all its sign related features off and set force resourcepack compat to true. That fixes the problem for me.

This was it. Thanks!
