### ISSUE TITLE
p_20355_ is null

### ISSUE THREAD

**Issue by ChanGrape** [MehVahdJukaar/amendments#150]
This crash has almost taken a month to figure out what mod caused it, but I have finally pinned it down to Amendments. I'm not sure what/how it makes the crash exactly from the crash report alone, but I'm hoping this is something that can be fixed. Crash report is here: https://pastebin.com/aFBWfLVU

**Comment by MehVahdJukaar** [comment]
From your log it doesn't look like it's amendments. Must me one of those mods that have a mixin in the entity class. They are quite a lot and are listed at the top of that log

**Comment by ChanGrape** [comment]
Could it be a moonlight lib issue then? The crash seems to happen only when moonlight lib and amendments are installed with improved mobs, which the creator of that mod says they don't mess with that part of any mobs in their mod.

**Comment by ChanGrape** [comment]
Yep it just crashed again just without amendments only. Darn, guess I'll keep looking, thanks for the help anyway!
