### ISSUE TITLE
Amendments potion cauldrons generating in villages

### ISSUE THREAD

**Issue by ghost** [MehVahdJukaar/amendments#152]
Cauldrons with random potion effects (including modded ones) generate in leatherworker village houses. No config option to disable generation either (1.2.12)
![2024-10-21_15 00 28](https://github.com/user-attachments/assets/7926c6c2-5a7e-4637-8c19-2b5ccce04e25)

**Comment by MehVahdJukaar** [comment]
Odd that's suppose to just be dye

**Comment by MehVahdJukaar** [comment]
fixed
