### ISSUE TITLE
Amendments and the Supplementaries mods are affecting mining 

### ISSUE THREAD

**Issue by TOXIC727** [MehVahdJukaar/amendments#158]
Hello i have installed this mod with the supplementaries mod along with it  and played on my world i notice that with any pickaxe will take forever to mine and not drop anything after mined. after i installed the mod the issue was solved but i still want to use this mod. is there any way of fixing this issue? i would like some assistance please.

**Comment by Shibward** [comment]
I had the same issue, i just updated to the most recent version fabric_1.21-3.0.5-alpha and that seemed to fix it
