### ISSUE TITLE
MC 1.20.1 Tripwire rendering bug

### ISSUE THREAD

**Issue by winnetrie83** [MehVahdJukaar/amendments#165]
When hanging a tool on the tripwire, the tripwire changes position. It goes 5 pixels up.
It's not gamebreaking ofcourse, but only fait to mention it.
![2024-11-25_16 35 12](https://github.com/user-attachments/assets/db316e79-771a-4ba3-88c0-e14dd3f6571b)
![2024-11-25_16 35 19](https://github.com/user-attachments/assets/7865f4df-03c6-411c-a659-feed73c2ae84)

This is for MC 1.20.1 and Forge 47.2.20

**Comment by MehVahdJukaar** [comment]
That's working as intended

**Comment by winnetrie83** [comment]
Ok, good enough. Personally i think it looks weird.

**Comment by MehVahdJukaar** [comment]
What's wrong with it? It would look way weirder if it was lowered as most of the tool you put in it would clip onto the block below
