### ISSUE TITLE
Falling block on carpet slab makes the world crash

### ISSUE THREAD

**Issue by Bwapt** [MehVahdJukaar/amendments#171]
Hi ! I've just found a bug where a falling block makes the world crash when it is dropped on a slab covered by a carpet. I've tried different type of slabs and carpets, and also other type of falling blocks, but every time the world crash after hurting the slab covered with carpet. I've also tried with stairs but in this case, the world doesn't crash.

Here are some info that might help you to debug and fix this bug :

### Versions

- **Minecraft** : 1.20.1
- **Fabric Loader** : 0.16.7

### Mods

- **Fabric API** : 0.92.2+1.20.1
- **Moonlight** : 1.20-2.13.37
- **Supplementaries** : 1.20-3.1.10
- **Amendments** : 1.20-1.2.12

### Steps to reproduce

1. Load a random world
2. Place a slab (any kind) in bottom position
3. Place a carpet (any kind) on the slab
4. Drop a falling block (any kind, tried with anvil and sand) on the slab
5. Watch your game crash

### Crash report

https://pastebin.com/7u4ngzU0

### Additional information

I just wan't to add that this bug has been found on a previous version of Supplementaries and Moonlight, so I don't think this has to do anything with them.

That is all I can give you for now, as I can't record my game without a graphics card. Feel free to ask me for any info you would need !

_Bwapt_

**Comment by MehVahdJukaar** [comment]
so actually this is consistent with current bell behavior. when shot with an arrow they dont trigger observers.
However the mod being amendments i think this would be a nice feature so i will add to both
