### ISSUE TITLE
Cake right click - inconsistent behaviour

### ISSUE THREAD

**Issue by bravely-beep** [MehVahdJukaar/amendments#174]
Right clicking on an uneaten double-cake block while holding a cake will do nothing.

Right clicking on a partially-eaten double-cake block will perform an action (taking a bite, or placing the held cake if Shift is held).

Tested with `amendments-1.20-1.2.12-fabric.jar`, Minecraft 1.20.0, Fabric Loader 0.16.9

**Comment by MehVahdJukaar** [comment]
fixed
