### ISSUE TITLE
Lantern arm models

### ISSUE THREAD

**Issue by Kuverr** [MehVahdJukaar/amendments#176]
![{5DDEF40F-91A2-4F7B-B796-718C98A9CEA9}](https://github.com/user-attachments/assets/50c6b0d4-62c4-42cd-ae19-cc654a262c9b)

The offhand arm model while holding a lantern is different than the mainhand.

Seems to be the slim playermodel arm with the regular texture squished.

1.21.1 Neoforge
Amendments 1.21-1.2.19

**Comment by MehVahdJukaar** [comment]
Show your skin pls

**Comment by Kuverr** [comment]
Sure
![{19FD5DB4-F56E-4BB8-988A-6A9127447F60}](https://github.com/user-attachments/assets/89e4d195-c508-4110-91ea-2d4fae4e8cb9)

[skin file](https://textures.minecraft.net/texture/284d4e5b254f30e34d228e8d82d4f37ee9076db474a242a079babd454b6fe3e)
I'm using the ETF mod for emissive textures on my skin, but I doubt it causes the bug

**Comment by Kuverr** [comment]
Yeah I just compared them and they're identical
My bad, I might just be a bit blind :sweat_smile:

![obraz](https://github.com/user-attachments/assets/f3b7f768-93a1-4997-a8d2-b159446a12f7)
