### ISSUE TITLE
Bell should trigger observer when it rings via chain pulling

### ISSUE THREAD

**Issue by somfunambulist** [MehVahdJukaar/amendments#177]
Currently bells only trigger observers when they receive a redstone signal, however it would add some interesting vertical input opportunities if a chain pull could also trigger them.

**Comment by MehVahdJukaar** [comment]
so actually this is consistent with current bell behavior. when shot with an arrow they dont trigger observers.
However the mod being amendments i think this would be a nice feature so i will add to both
