### ISSUE TITLE
Specific discs not playing in jukebox

### ISSUE THREAD

**Issue by Emery319** [MehVahdJukaar/amendments#18]
NeoForge: 47.1.96

Amendments: 1.20-1.0.11
Supplementaries: 1.20-2.8.1
Moonlight: 1.20-2.10.3

Cloud Storage: 1.4.0
Citadel: 2.5.3

Eidolon Repraised: 1.20.1-0.3.8.1
Curios API: 5.5.0+1.20.1

Aquamirae: 6.API15
Obscure API: 15

Disc from "Cloud Storage" are deleted after right clicking into the Jukebox.
![2024-02-23_17 18 59](https://github.com/MehVahdJukaar/amendments/assets/124550540/b34022ef-1703-4faa-98c3-b01bd3909b0b)

Discs from "Eidolon Repraised" and "Aquamirae" interact correctly with the Jukebox, but playback stops after a few seconds.
![2024-02-23_17 19 11](https://github.com/MehVahdJukaar/amendments/assets/124550540/72048a7e-7cb1-4eaf-99ba-4b3c596de946)
![2024-02-23_17 19 24](https://github.com/MehVahdJukaar/amendments/assets/124550540/6c40b8c0-0f1d-4c6c-8a8e-08d5d8775179)

**Comment by Emery319** [comment]
If these issues need to be fixed by the original mod author, is it possible to add an option to disable the Jukebox feature in the config?

**Comment by MehVahdJukaar** [comment]
so amendments jukebox feature is purely visual. it does not affect if a disc can be played or not

**Comment by Emery319** [comment]
lol, thanks!

**Comment by MehVahdJukaar** [comment]
youshould report to them. crazy how many mods didnt update properly to 1.20

**Comment by Emery319** [comment]
Of course, I just submitted an Issue to Eidolon Repraised. Aquamirae and Cloud Storage already have this issues, but those two mods haven't been updated in over half a year, so I might have to make a disc mod myself to fix this :(
