### ISSUE TITLE
Game won't even load

### ISSUE THREAD

**Issue by DrCookie95** [MehVahdJukaar/amendments#2]
I just received the mesage that some features from the Supplementaries mod were ported to Amendments, though it seems that this mod makes my modpack crash before it has even may chances of loading. Might be compatability problems, but I'm not sure.

**Comment by misfit-stag** [comment]
Same problem here.

[latest.log](https://github.com/MehVahdJukaar/amendments/files/14362718/latest.log)

**Comment by bones384** [comment]
Same here :(

**Comment by Rozarke** [comment]
same

**Comment by DrCookie95** [comment]
Guys Update: They released a new version, it now works
