### ISSUE TITLE
Alex's Caves Acid Missing Texture in Cauldron

### ISSUE THREAD

**Issue by mxnmnm** [MehVahdJukaar/amendments#20]
![2024-02-23_03 28 04](https://github.com/MehVahdJukaar/amendments/assets/8508976/315b2d78-c1b3-4635-9d36-98c44063d19f)
When I put the acid in it's fine but when you leave and rejoin the world it loses its texture and stops damaging mobs :(

**Comment by MehVahdJukaar** [comment]
use /data get on the block and tell me what it shows

**Comment by MehVahdJukaar** [comment]
also try with newest moonlight version

**Comment by mxnmnm** [comment]
fixed
