### ISSUE TITLE
Amendments causing crash with Rats cheesemaking in cauldrons

### ISSUE THREAD

**Issue by ianm1647** [MehVahdJukaar/amendments#21]
the title says it all, here's the crash report (this is on a dedicated server)
[https://pastebin.com/HkaLEgvZ](https://pastebin.com/HkaLEgvZ)

**Comment by mxnmnm** [comment]
I don't get a crash but I cannot make any cheese from rats :(

**Comment by ianm1647** [comment]
thank you for fixing it!
