### ISSUE TITLE
Modrinth support

### ISSUE THREAD

**Issue by Enderteck** [MehVahdJukaar/amendments#23]
As modrinth is starting to be the new standard and because supplementaries and squared are on Modrinth, I think this mod should be there too.

It's also better (open source !).

**Comment by MehVahdJukaar** [comment]
I do support modrinth but I don't think it's necessarily better. I do like cursefirge. To prove this point I'll just tell you that the only reason that they mod "isn't on modrinth" is because they haven't approved it there, it's been a week and not approved while curseforg only took 2 days

**Comment by Enderteck** [comment]
I was wondering if it was an issue with them not yet approving it. I didn't know this was such a new mod lol. Thx for the answer
