### ISSUE TITLE
When you put water in a cauldron, the color of the water you see is not blue, but white

### ISSUE THREAD

**Issue by tankplanelaserkoala** [MehVahdJukaar/amendments#25]
File Version : 1.0.16

moonlight Version : 2.10.8

loader : Forge 47.2.20

https://github.com/MehVahdJukaar/amendments/assets/157739795/e203a7ea-a078-460a-89c9-b0fc753aedd6

**Comment by MehVahdJukaar** [comment]
So you have a mod that messes with colours? Biome blend? Rendering mod?

**Comment by tankplanelaserkoala** [comment]
no

**Comment by tankplanelaserkoala** [comment]
It still doesn't work, so I'll refer to the mod file in the above article.

**Comment by MehVahdJukaar** [comment]
Try with just the mod. It mus the something messing with block colors

**Comment by tankplanelaserkoala** [comment]
![image](https://github.com/MehVahdJukaar/amendments/assets/157739795/b29e465e-e6ad-422f-8e37-86df0fdc3930)

I've tried this, but the color of the cauldron water remains the same

**Comment by MehVahdJukaar** [comment]
what forge version are you on?

**Comment by tankplanelaserkoala** [comment]
I'm using version 47.2.20

**Comment by tankplanelaserkoala** [comment]
![image](https://github.com/MehVahdJukaar/amendments/assets/157739795/53c4856f-fb76-49e9-8924-88f947bfbb71)

**Comment by tankplanelaserkoala** [comment]
![image](https://github.com/MehVahdJukaar/amendments/assets/157739795/9a1c9778-b4ce-4a74-9766-a3328eb5cfbb)
I tried it by upgrading the version, but it's still the same.

**Comment by tankplanelaserkoala** [comment]
Go into the texture pack and make sure the mod resource is above the vanilla resource.

**Comment by Raeligascu** [comment]
> Go into the texture pack and make sure the mod resource is above the vanilla resource.

You should pin this!!! I spent forever trying to fix this. Thank you so much!!
