### ISSUE TITLE
The color of the potion shown by the Brewing Stands does not change.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [MehVahdJukaar/amendments#27]
File Version : 1.0.16

moonlight Version : 2.10.8

loader : Forge : 47.2.20

https://github.com/MehVahdJukaar/amendments/assets/157739795/0a9ffb3f-275a-4e7e-8216-fd457e353e27

**Comment by MehVahdJukaar** [comment]
Do you have a texture pack?

**Comment by tankplanelaserkoala** [comment]
no

**Comment by MehVahdJukaar** [comment]
yeah idk i cant replicate. i tested on a live instance 47.2.0 forge with just a couple other mods
![image](https://github.com/MehVahdJukaar/amendments/assets/24719182/ea0efa43-4594-4e3d-9a75-bf97918ec9d6)

**Comment by tankplanelaserkoala** [comment]
What the hell

**Comment by MehVahdJukaar** [comment]
open your resource pack folder. see if the moonlight genereated assets have a high priority (they do by default as they are near the top)

**Comment by MehVahdJukaar** [comment]
I'm 99% sure that your issue. Now curios why was was that priority lowered? by default its always option of both vanilla and mod resources

**Comment by tankplanelaserkoala** [comment]
https://github.com/MehVahdJukaar/amendments/assets/157739795/70dd976c-3451-46d8-8ec5-3cfee8183dc9

Yes, that's high.

**Comment by tankplanelaserkoala** [comment]
Oh thank you, you were right.
