### ISSUE TITLE
Is there a way to make potions in cauldrons?

### ISSUE THREAD

**Issue by ALEILGOD** [MehVahdJukaar/amendments#28]
Hi, i'm trying to make potions in cauldrons but it seems like nothing is working.
Do someone know how to do it?

**Comment by MehVahdJukaar** [comment]
nope. cauldrons are for mixing. brewing starnds are for brewing

**Comment by ALEILGOD** [comment]
Thanks. But when i mix two different potions it will make me an uncraftable potions with no effects
Example:
Strength + Swiftness=Uncraftable potions with no effects

**Comment by MehVahdJukaar** [comment]
hmmmm must be a compatibility issue

**Comment by ALEILGOD** [comment]
Ok, is there a way to fix it?

**Comment by MehVahdJukaar** [comment]
no, unless the mod that its conflciting is found

**Comment by ALEILGOD** [comment]
I tried with only Amendments but it now says mixend potion with no effects.
Same potion type used

**Comment by MehVahdJukaar** [comment]
forge or fabric? are you on neoforge?

**Comment by ALEILGOD** [comment]
forge

**Comment by ALEILGOD** [comment]
47.2.0

**Comment by ALEILGOD** [comment]
1.20.1

**Comment by MehVahdJukaar** [comment]
yeah idk i cant replicate. I just tested on a live instance with 47.2.0 forge with a couple other mods and latest mod version
![image](https://github.com/MehVahdJukaar/amendments/assets/24719182/3e58e218-798b-41d0-9576-6064b0d20c51)

**Comment by ALEILGOD** [comment]
I'm sending a video of what is happening

**Comment by MehVahdJukaar** [comment]
use /data get on the cauldron once you crafted those

**Comment by ALEILGOD** [comment]
![immagine_2024-02-25_161151138](https://github.com/MehVahdJukaar/amendments/assets/116183327/70179a0d-1a86-4c0e-8b0a-fae7e289e0ea)

![Screenshot 2024-02-25 161129](https://github.com/MehVahdJukaar/amendments/assets/116183327/b95fc681-167c-42b5-bf57-d4350bdf171b)

**Comment by ALEILGOD** [comment]
there is no custom effect

**Comment by MehVahdJukaar** [comment]
which potions did you use exactly? which level

**Comment by ALEILGOD** [comment]
Strenght I (3:00), Swiftness I (3:00) I use Prism Launcher

**Comment by MehVahdJukaar** [comment]
try the new version

**Comment by ALEILGOD** [comment]
Of the mod?

**Comment by ALEILGOD** [comment]
I already have the latest version
1.20-1.0.15

**Comment by ALEILGOD** [comment]
Thanks
