### ISSUE TITLE
Weird Signpost Generation.

### ISSUE THREAD

**Issue by cartooneric84** [MehVahdJukaar/amendments#29]
Can this be looked at?
![2024-02-25_08 29 54](https://github.com/MehVahdJukaar/amendments/assets/86167550/fbf6caf6-9d30-4d19-8248-a3a7df827fa1)

**Comment by MehVahdJukaar** [comment]
lmao

**Comment by MehVahdJukaar** [comment]
version?

**Comment by cartooneric84** [comment]
> version?

Amendments version 1.20.1.0.16 for Forge.

**Comment by MehVahdJukaar** [comment]
should be fixed
