### ISSUE TITLE
Issues with the Supplementaries Squared lanterns

### ISSUE THREAD

**Issue by PurpleMists** [MehVahdJukaar/amendments#3]
All lanterns are missing a handle texture when placed on a wall. 
The Copper Lantern model appears inside of the player hand when held. 
The Crimson Lantern becomes unbreakable without a pickaxe when on a wall (as seen in the Jade tooltip). When placed otherwise, it can be broken with an empty hand.

Pictures of the issues:
![2024-02-21_20 55 39](https://github.com/MehVahdJukaar/amendments/assets/80048283/1d83df1a-6792-4a24-91ba-0597ebd2f51a)
![2024-02-21_20 56 40](https://github.com/MehVahdJukaar/amendments/assets/80048283/d356f622-a582-45d7-b548-8f8f39d7d442)
![2024-02-21_20 58 23](https://github.com/MehVahdJukaar/amendments/assets/80048283/60336a7e-f8e9-4fdb-b6f0-749279edd817)

**Comment by ALEILGOD** [comment]
Try to add a resource pack generator mod like Load My Resources or similar

**Comment by MehVahdJukaar** [comment]
does this stull happen with latest version?

**Comment by PurpleMists** [comment]
Yes, it is.

![image](https://github.com/MehVahdJukaar/amendments/assets/80048283/0453e6d4-a713-477e-b88e-83d4802f0d3f)
