### ISSUE TITLE
crash LiquidCauldronBlock?

### ISSUE THREAD

**Issue by Rodrigo816** [MehVahdJukaar/amendments#32]
I got crash while playing it seams related to this mod as far I can understand.

[crash-2024-02-26_22.17.53-client.txt](https://github.com/MehVahdJukaar/amendments/files/14412374/crash-2024-02-26_22.17.53-client.txt)

**Comment by MehVahdJukaar** [comment]
check your moonlight lib is updated. That happened when trying to mix 2 potions with inverse effects. The reason why it crashes is because the config for that stuff somehow returned null. I dont really know how that was possible so if that still happens try deleting your configs. Please tell me if you find anything about this

**Comment by Rodrigo816** [comment]
I got the error again while exploring, I was creative mode just exploring around
moonlight version is: 1.20-2.10.9 (most recent)
here the logs:
[crash-2024-02-28_22.41.34-client.txt](https://github.com/MehVahdJukaar/amendments/files/14440989/crash-2024-02-28_22.41.34-client.txt)

**Comment by MehVahdJukaar** [comment]
Were you on a server?

**Comment by MehVahdJukaar** [comment]
Als

**Comment by MehVahdJukaar** [comment]
O can you

**Comment by Rodrigo816** [comment]
> Also can you send me your mod configs?

I'm in a singleplayer world
I belive u want amendments config its all by default didn't change anything

common.toml
https://github.com/Rodrigo816/Create-chronicles-bosses-and-beyond/blob/main/config/amendments-common.toml

client.toml
https://github.com/Rodrigo816/Create-chronicles-bosses-and-beyond/blob/main/config/amendments-client.toml

It's probably a mod compatibility issue since I have 240+ mods installed.

**Comment by Rodrigo816** [comment]
[cauldron.inverse_potions]
		"minecraft:mining_fatigue" = "minecraft:haste"
		"minecraft:instant_health" = "minecraft:instant_damage"
		"minecraft:unluck" = "minecraft:luck"
		"minecraft:instant_damage" = "minecraft:instant_health"
		"minecraft:weakness" = "minecraft:strength"
		"minecraft:slowness" = "minecraft:speed"
		"minecraft:haste" = "minecraft:mining_fatigue"
		"minecraft:strength" = "minecraft:weakness"
		"minecraft:speed" = "minecraft:slowness"
		"minecraft:luck" = "minecraft:unluck"
		
		
		Seams related to this? or a mod that modifies potions?

**Comment by MehVahdJukaar** [comment]
weird that seems correct. does this still happen with new versions? try spawning a swamp hit in superflat

**Comment by Rodrigo816** [comment]
I've noticed that there's almost a new update every day. I always play on the most recent version and haven't encountered a single crash so far. If it happens again, I'll reopen the issue.
