### ISSUE TITLE
Cakechomps compatibility issue causes game crash when both Amendments and Supplementaries are On

### ISSUE THREAD

**Issue by ZeTrashMan** [MehVahdJukaar/amendments#36]
When Cakechomps, Amendments and Supplementaries are activated, Placing a double cake or eating from a double cake causes the game to crash. Weirdly, it doesn't happen if Supplementaries is off and only both Cakechomps and amendments are on.

I've also reported this compatibility issue to the creator of Cakechomps.

Also, here is the latest.log.
[latest.log](https://github.com/MehVahdJukaar/amendments/files/14471169/latest.log)

**Comment by MehVahdJukaar** [comment]
They need to update their compat. On their side
