### ISSUE TITLE
Carpeted stairs going invisible and see through

### ISSUE THREAD

**Issue by thicccyniccy** [MehVahdJukaar/amendments#40]
When trying to create carpeted stairs, they go invisble and see through 
these are the mods i have installed:
![image_2024-03-06_012002573](https://github.com/MehVahdJukaar/amendments/assets/162413997/7e501ac9-d7d2-4b7b-87c0-84e6f2cd80db)

these are logs:
https://mclo.gs/EnFp3SV

no clue what is going wrong here!!

**Comment by MehVahdJukaar** [comment]
what is going on is that you are using sodium

**Comment by MehVahdJukaar** [comment]
and sodium isnt meant to be used with other mods as it breaks fabric api itself. use embeddium fabric

**Comment by thicccyniccy** [comment]
> and sodium isnt meant to be used with other mods as it breaks fabric api itself. use embeddium fabric

oh lol let me use that and see if it fix

**Comment by thicccyniccy** [comment]
@MehVahdJukaar switching to embeddium fixed it sorry lol i didnt know
