### ISSUE TITLE
(Compatibility Request) NewWorld Support

### ISSUE THREAD

**Issue by BlueIsADude** [MehVahdJukaar/amendments#42]
NewWorld's Fir Hanging Signs are currently unsupported by amendments, making them appear as Oak Hanging Signs. 
![image](https://github.com/MehVahdJukaar/amendments/assets/159506207/5637b73f-deef-4a2d-8a5e-dabc712625dc)
This clearly wouldnt fit well in builds that mainly use fir wood, so a fix for this would be greatly appreciated!

Note that turning off all client-side hanging sign features fixes this issue:
![image](https://github.com/MehVahdJukaar/amendments/assets/159506207/b59a739e-e0d1-47f3-a4ae-713e7c6ca59d)

**Comment by MehVahdJukaar** [comment]
If they don't work it's their issue for not making them properly. They likely don't populate the hanging sign texture map with their texture. Not only that but their renderer get texture method doesn't return the texture either. There's 0 reason to register a new renderer for hanging signs. A new tile entity too fir that reason
