### ISSUE TITLE
Cauldron creates missing texture when mixing conflicting potions

### ISSUE THREAD

**Issue by Jackmann527** [MehVahdJukaar/amendments#43]
Cauldron's potion water texture is replaced with a missing texture when mixing potions with conflicting effects (instant health/instant harming, strength/weakness, etc.)
tested on fresh install
game version: 1.20.1
mod version: 1.1.8
![2024-03-07_16 03 57](https://github.com/MehVahdJukaar/amendments/assets/162640052/b8a96e37-92a0-4b66-b810-1ca868127a58)

**Comment by MehVahdJukaar** [comment]
its supposed to go boom 💀

**Comment by Jackmann527** [comment]
I hear the boom sound effect, but the only other thing that happens is the missing texture.

**Comment by MehVahdJukaar** [comment]
should be fixed

**Comment by Jackmann527** [comment]
Confirmed
