### ISSUE TITLE
Curseforge Download/Installation Failure

### ISSUE THREAD

**Issue by HammerBones** [MehVahdJukaar/amendments#45]
Version 1.1.9 has a mod file integrity check failure for manual download and through curseforge. Gets flagged by anti-virus and the curseforge client. Cannot update the mod due to this.

Defender flags it through both client download and manual as Trojan:Script/Wacatac/B!ml

**Comment by MehVahdJukaar** [comment]
nothing i can do about this. report to microsoft defender

**Comment by TheSnowyChickens** [comment]
Hello,
same here with MS Defender on both 1.1.10 versions. (btw why 2 .10 versions ? xD)

Is there no way to fix this from your side ?

**Comment by MehVahdJukaar** [comment]
No, obviously not. It's a windows defender issue
