### ISSUE TITLE
offset hanging lanterns at distance

### ISSUE THREAD

**Issue by kerrschtein** [MehVahdJukaar/amendments#46]
using: amendments-1.20-1.1.10 on fabric

pictured at distance with zoom here:
![image](https://github.com/MehVahdJukaar/amendments/assets/55864549/c4bba66b-4f0d-469f-be53-5513962560c9)
![image](https://github.com/MehVahdJukaar/amendments/assets/55864549/2c86fa4e-0a4a-491c-8c22-f136d91e3e43)

pictured closer here:
![image](https://github.com/MehVahdJukaar/amendments/assets/55864549/a53132b0-103a-454f-9083-85acaf282eee)
![image](https://github.com/MehVahdJukaar/amendments/assets/55864549/640e5c01-54bf-44f4-9fdf-9d7fb5f26923)

this happens to quite a few lanterns, not just ones from any specific mod.

**Comment by MehVahdJukaar** [comment]
fixed
