### ISSUE TITLE
[1.20.1] v1.1.10 - Bug with Quark's Vertical Slabs

### ISSUE THREAD

**Issue by Zetalas** [MehVahdJukaar/amendments#47]
Hiya,
I've been playing with the latest build of Quark and Amendments. 
When cauldron connecting to fences is enabled, the connection blocks (bars, panes, etc.) are unable to connect to Quark's vertical slabs. Disabling this in the config results in the expected behaviour.

Latest Neoforge Build for 1.20.1
Quark v4.0 - 438
Amendments v1.1.10

**Comment by MehVahdJukaar** [comment]
cant replicate. 

![image](https://github.com/MehVahdJukaar/amendments/assets/24719182/d6a90737-89be-4b11-ae65-547e453d48dc)

**Comment by Zetalas** [comment]
After running more tests with only Quark/Amendments installed, I still encountered this until I emptied my config folder and now am unable to replicate the issue.
