### ISSUE TITLE
Unable to write into a Book and Quill when the item is in a lectern

### ISSUE THREAD

**Issue by JakeHumphries4** [MehVahdJukaar/amendments#53]
I can write fine into a book and quill when in my inventory (vanilla UI), however when the book is in the lecture with the modified UI from amendments, it states I am on Page 1 of 0, and cannot type. The caret is visible in the book, but typing doesn't do anything. Changing the ink colour or font style changes nothing.

![ammendments_issue](https://github.com/MehVahdJukaar/amendments/assets/34066256/aa3fd8ac-085a-42c0-8e54-4dccc26fa8a6)

**Comment by MehVahdJukaar** [comment]
remove the mod and try without. does it still happen?

**Comment by JakeHumphries4** [comment]
Without the mod, you cannot type in lecterns, as is intended in vanilla minecraft.

**Comment by MehVahdJukaar** [comment]
True. I can't replicate, not sure what causes this

**Comment by JakeHumphries4** [comment]
This can likely be closed, but I seem to have found the issue and wondered if you have any insight. The book that doesn't work has NBT data of {pages: []} (empty page), whereas a regular book has no data. Why could this be the case?

**Comment by MehVahdJukaar** [comment]
Hm how did you obtain that

**Comment by JakeHumphries4** [comment]
I clicked the sign book button, and back out of the menu. The book remained as a book and quill, and added the tag. I haven't checked if this is the same with a new book however.

**Comment by MehVahdJukaar** [comment]
is this still an issue?

**Comment by JakeHumphries4** [comment]
Seemed to be a data error with the item itself iirc. I'll close with this comment.
