### ISSUE TITLE
Version 1.11 causes a dedicated server crash on boot

### ISSUE THREAD

**Issue by moninformateur** [MehVahdJukaar/amendments#54]
When using the latest Amendments 1.11 on Minecraft-**Forge** 1.20.1-**47.1.3** with the Syntra Connector on a dedicated server, said server will not be able to start, resulting in the following [log](https://mclo.gs/Q0mXi4F).

Issue is absent from the client-side or singleplayer server. Using version 1.10 results in working dedicated server.

**Comment by MehVahdJukaar** [comment]
update moonlight lib. upate your mods

**Comment by moninformateur** [comment]
Sorry you're right. Had a brainfart when updating the dedicated server's mod.
