### ISSUE TITLE
Cannot turn off the new lantern holding model client side

### ISSUE THREAD

**Issue by SolarThemedDance** [MehVahdJukaar/amendments#55]
So i am playing on an origin server using an origin that very heavily uses lanterns that just had to update due to a glitch on April first. I need to have a lantern on me at all times and me and the rest of the server are vaguely distressed with this new model that we cannot turn off. Would it be possible to add a switch to revert both the first and third person models to og minecraft?

**Comment by MehVahdJukaar** [comment]
There is one. It's tag driven and tied to the wall lantern list.

**Comment by MehVahdJukaar** [comment]
plus theres even a config...

**Comment by SolarThemedDance** [comment]
> plus theres even a config...

To turn off the models of how you hold it? Like what the arm does in both first and third person

**Comment by SolarThemedDance** [comment]
Would it be possible to make it so those could be disabled client side? Like the arm holding up the lantern and how the lantern is held in third

**Comment by MehVahdJukaar** [comment]
As I've said there's a config for that

**Comment by SolarThemedDance** [comment]
im guessing that's the unsupported entry in the configs
![image_2024-04-03_162607731](https://github.com/MehVahdJukaar/amendments/assets/165858046/77302993-7d00-401e-beca-e006a813058a)

**Comment by MehVahdJukaar** [comment]
no its the last one. they all have comments explaining what they do btw. that config mod shows that

**Comment by SolarThemedDance** [comment]
> no its the last one. they all have comments explaining what they do btw. that config mod shows that

That just gets rid of the lantern in third person, I want to still be able to see the lantern not make it invisible. It also does not turn off being able to see the arm holding the lantern in first person. Is it just glitched on the server?

**Comment by MehVahdJukaar** [comment]
i am confused. that config will make the lantern animation go away and lantern will be back in 2d like in vanilla. Config is client sided and requires client reboot

**Comment by RemasteredArch** [comment]
Hey, another member of that server stepping in to reply for @SolarThemedDance. Apologies if they haven't been helpful in the issue, they're not a developer and aren't used to making informative bug reports/feature requests.

I can confirm that restarting does return lantern rendering to how they wanted using a mostly fresh Minecraft install on `fabric-loader-0.15.9-1.20.1`, using `amendments-1.20-1.1.13-fabric`, `cloth-config-11.1.118-fabric`, `fabric-api-0.92.0+1.20.1`, `modmenu-7.2.2`, and `moonlight-1.20-2.11.9-fabric`.
That being said, I think that it would be helpful to communicate clearly which settings require a restart, as to the user, it looks like that setting only affects third person.

Looks like, however, the setting does nothing (even after a restart) when using the modpack that I use to play on the server. This is unlikely to be an amendments-specific issue, as the pack has 99 mods total (by measurement of the number of `*.jars` in `mods/`) as well as an older version of some mods (e.g. Amendments 1.1.12). I'll try to work with @SolarThemedDance or another server member to look into this further, I don't think that troubleshooting this should be your responsibility. Will update this thread if we discover the conflicting mod(s).

**Comment by SolarThemedDance** [comment]
> Hey, another member of that server stepping in to reply for @SolarThemedDance. Apologies if they haven't been helpful in the issue, they're not a developer and aren't used to making informative bug reports/feature requests.
> 
> I can confirm that restarting does return lantern rendering to how they wanted using a mostly fresh Minecraft install on `fabric-loader-0.15.9-1.20.1`, using `amendments-1.20-1.1.13-fabric`, `cloth-config-11.1.118-fabric`, `fabric-api-0.92.0+1.20.1`, `modmenu-7.2.2`, and `moonlight-1.20-2.11.9-fabric`. That being said, I think that it would be helpful to communicate clearly which settings require a restart, as to the user, it looks like that setting only affects third person.
> 
> Looks like, however, the setting does nothing (even after a restart) when using the modpack that I use to play on the server. This is unlikely to be an amendments-specific issue, as the pack has 99 mods total (by measurement of the number of `*.jars` in `mods/`) as well as an older version of some mods (e.g. Amendments 1.1.12). I'll try to work with @SolarThemedDance or another server member to look into this further, I don't think that troubleshooting this should be your responsibility. Will update this thread if we discover the conflicting mod(s).

<3

**Comment by IcePenguin1** [comment]
Hello, third server member here. I troubleshot this and the solution is to just update the server to the newest version.

In testing `amendments-1.20-1.1.12-fabric` and `amendments-1.20-1.1.11-fabric` both show the holding model in first person, and also don't show a lantern in third person despite having the config off. However, `amendments-1.20-1.1.13-fabric` and `amendments-1.20-1.1.14-fabric` both have this feature working properly. 

As a side note I would recommend that you have some sort of message telling the user that they have to reboot their game for the config to go into affect. 

Sorry for this whole thing, but thank you for your time!
