### ISSUE TITLE
Right-clicking the quill in the new Book and Quill UI crashes the game

### ISSUE THREAD

**Issue by Snooziepup** [MehVahdJukaar/amendments#58]

**Comment by MehVahdJukaar** [comment]
I need latest.log

**Comment by MRRollMan** [comment]
I have the same problem on the server, here is the crash log 
[crash-2024-04-25_17.25.23-server.txt](https://github.com/MehVahdJukaar/amendments/files/15111647/crash-2024-04-25_17.25.23-server.txt)

**Comment by MehVahdJukaar** [comment]
is this still a thing?

**Comment by MRRollMan** [comment]
The server stopped crashing, but lectern does not open and an error is displayed in the console.
[latest.log](https://github.com/MehVahdJukaar/amendments/files/15286497/latest.log)

**Comment by MehVahdJukaar** [comment]
I cant replicate. The second log seems a bukkit issue

**Comment by MRRollMan** [comment]
Yes, I tried repeating with the new version on a regular forge server and the error is not observed. I think the issue can be closed if its author doesn't respond. 
**Thanks for the fix!**
