### ISSUE TITLE
DirectionalCakeBlock doesnt call super in appendProperties causing crash with other mods

### ISSUE THREAD

**Issue by Linguardium** [MehVahdJukaar/amendments#60]
https://github.com/MehVahdJukaar/amendments/blob/c0e228b012683bcc95a57aa67fca7f83021370aa/common/src/main/java/net/mehvahdjukaar/amendments/common/block/DirectionalCakeBlock.java#L165-L167

Failing to call super here causes issues with mods that add properties to the Cake block (like Spoiledz)
Ideally, call super, then add your properties to the builder

**Comment by MehVahdJukaar** [comment]
Infact believe it or not but i remembered that it NOT calling super was a hack "solution" to this very same exact problem from another mod that would add the waterlogged property to cakes. Since double cakes are on their own waterlogged and vanilla does not allowd double property definition that would cause issues. This is the reason why its actually safer to not call super and many vanilla blocks do it too. Fact is injecting properties via that method is never really safe unless you use a library that has that figured out

**Comment by Linguardium** [comment]
> calling super would indeed be better. I try to do it all the time and that is indeed an oversight. That said if a mod forcefully adds properties to a vanilla class and is NOT prepared for mods NOT calling super, that's very bad practice and it's 100% their problem as that is a totally valid scenario that will happen. I've done stuff like that before the proper way, simply checking if the property exist is enoguh before accessing

the issue comes in when entering the initializer of the class as the setDefaultBlockState sets the default state of the property you skip adding when you skip the parent class's property builder

**Comment by MehVahdJukaar** [comment]
There too one can check if the property exists or not

**Comment by MehVahdJukaar** [comment]
You can thumb down without adding much to the argument, doesn't change much. Fact is adding a new property to other mods blocks is always risky unless you use a library that has it figured it out or take extra care. Subclasses from mods can and will not call super, on any method. That's how inheritance works and the ones modifying vanilla classes must be prepared to deal with it as they are the one doing something risky

**Comment by MehVahdJukaar** [comment]
In other words it's fair to say "it would be better for compat if you called super here and there" but not to say "if you don't do that, that other mod will crash" as that is entirely their issue

**Comment by Linguardium** [comment]
i understand the underlying issue here and that its a choice between crashing mods that add their own block properties to vanilla blocks (current situation) or having other mods crash yours due to them adding vanilla block properties to vanilla blocks (previous situation that you worked around here).

While I disagree that crashing mods that add non-vanilla properties to vanilla blocks is the "right" choice, I concede that it is a personal opinion. The only alternative I have is to not extend vanilla blocks if you are going to run into issues calling the parent class constructor regardless of choice (which only creates issues if mods add things to the Block/AbstractBlock classes themselves)
