### ISSUE TITLE
Crash w/ Moonlight 

### ISSUE THREAD

**Issue by ereese99** [MehVahdJukaar/amendments#66]
[crash-2024-04-19_22.21.05-server.txt](https://github.com/MehVahdJukaar/amendments/files/15048962/crash-2024-04-19_22.21.05-server.txt)

**Comment by scotus-1** [comment]
[crash-2024-04-20_19.44.54-server.txt](https://github.com/MehVahdJukaar/amendments/files/15050796/crash-2024-04-20_19.44.54-server.txt)

Same issue with structure placement.

**Comment by MehVahdJukaar** [comment]
do you have cyanide mod?

**Comment by scotus-1** [comment]
Yes

**Comment by MehVahdJukaar** [comment]
And have you tried without?

**Comment by scotus-1** [comment]
No, sorry I just didn't consider Cyanide being possible incompatible. If I find it to fix the problem, is there any way to keep cyanide? It is really useful for debugging world generation in a large modpack.

**Comment by scotus-1** [comment]
I think that fixed it, I haven't encountered a crash after generating a lot of structures. I checked the Cyanide issue tracker and I guess its been having problems, even though its just for error reporting. Thank you so much

**Comment by MehVahdJukaar** [comment]
i opened an issue there
