### ISSUE TITLE
Crash when using wool on a cauldron containing the same dye colour as the wool

### ISSUE THREAD

**Issue by ManaStar** [MehVahdJukaar/amendments#68]
## Versions:
- Amendments 1.20-1.1.22 (Fabric)
- Moonlight Lib fabric_1.20-2.11.12
- Fabric API 0.92.1+1.20.1

## Log:
https://mclo.gs/7HMc5Hi

**Comment by craftish37** [comment]
Possibly related, got this issue with cauldrons while loading chunks :
[crash-2024-04-23_17.09.18-server.txt](https://github.com/MehVahdJukaar/amendments/files/15078934/crash-2024-04-23_17.09.18-server.txt)

Don't mind the horrendous number of mods btw
Same setup as above

**Comment by MehVahdJukaar** [comment]
fixd

**Comment by craftish37** [comment]
> Possibly related, got this issue with cauldrons while loading chunks : [crash-2024-04-23_17.09.18-server.txt](https://github.com/MehVahdJukaar/amendments/files/15078934/crash-2024-04-23_17.09.18-server.txt)
> 
> Don't mind the horrendous number of mods btw Same setup as above

Still got the issue, here's new logs from the server this time
[crash-report](https://github.com/MehVahdJukaar/amendments/files/15327166/crash-2024-05-15_23.28.15-server.txt)

**Comment by MehVahdJukaar** [comment]
And are you 100% sure you are not using Cyanide? that mod is known to currently break all other mod added datapack registries

**Comment by craftish37** [comment]
Oh I’ll be sure to try without but I never had any issues with Cyanide, even knowing how often I use datapacks 🤔
Thanks for the input anyway

**Comment by MehVahdJukaar** [comment]
That's because it's likely you never used another mod with a dayapack registry

**Comment by craftish37** [comment]
So far so good, I guess I won’t have problems now
Thanks for the help 👍
