### ISSUE TITLE
Carpet Stairs crashes 

### ISSUE THREAD

**Issue by 3dguru** [MehVahdJukaar/amendments#71]
When putting carpet on any type of stair variant it crashes the games/server

 Encountered an unexpected exception
01.05 02:10:29 [Server] [INFO] java.lang.NoClassDefFoundError: io/github/flemmli97/flan/api/permission/PermissionRegistry
01.05 02:10:29 [Server] [INFO] at net.mehvahdjukaar.amendments.integration.FlanCompat.canPlace(FlanCompat.java:34) ~[amendments-1.20-1.1.22-fabric.jar:?]
01.05 02:10:29 [Server] [INFO] at net.mehvahdjukaar.amendments.events.behaviors.InteractEvents.onItemUsedOnBlock(InteractEvents.java:136) ~[amendments-1.20-1.1.22-fabric.jar:?]
01.05 02:10:29 [Server] [INFO] at net.mehvahdjukaar.amendments.events.ModEvents.onRightClickBlock(ModEvents.java:20) ~[amendments-1.20-1.1.22-fabric.jar:?]
01.05 02:10:29 [Server] [INFO] at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41) ~[fabric-events-interaction-v0-0.6+1802ada577-6fc36030f9858a64.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_3225.handler$bcm000$fabric-events-interaction-v0$interactBlock(class_3225.java:2087) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_3225.method_14262(class_3225.java) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
01.05 02:10:29 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
01.05 02:10:29 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: io.github.flemmli97.flan.api.permission.PermissionRegistry
01.05 02:10:29 [Server] [INFO] at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
01.05 02:10:29 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
01.05 02:10:29 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
01.05 02:10:29 [Server] [INFO] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
01.05 02:10:29 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]

**Comment by MehVahdJukaar** [comment]
fixd
