### ISSUE TITLE
Confict with Flan 1.20.1-1.10.0, Minecraft server shutdown

### ISSUE THREAD

**Issue by farlydapamanis** [MehVahdJukaar/amendments#77]
Amendments conflict with Flan mod, every time i claim land using flan, minecraft server shutdown. this is the log
https://paste.gg/p/anonymous/492e12812fe24adc9545ba5673dcb105

Minecraft Version 1.20.1
Fabric Loader 0.15.10
Flan 1.20.1-1.10.0
I'm using the latest Amendments mod for minecraft 1.20.1

Steps to reproduce: using golden hoe, and right click a block

**Comment by MehVahdJukaar** [comment]
use newer version of both mods
