### ISSUE TITLE
Double carpeted slabs

### ISSUE THREAD

**Issue by nimbXnumb** [MehVahdJukaar/amendments#8]
Mod version:
1.20-1.0.8
Minecraft version:
1.20.1 Fabric

Description:
Using carpet on a double slabs (or upper slab) causes visual bug as if it was a single bottom slab.

![image](https://github.com/MehVahdJukaar/amendments/assets/117385950/94a38857-6dd0-4f50-a5ac-19e23ad99d34)

**Comment by MGJerry** [comment]
Can confirm this is the case. Carpet on upper (upside-down) stairs works fine.

**Comment by MehVahdJukaar** [comment]
this with the latest version?

**Comment by nimbXnumb** [comment]
> this with the latest version?

Yes, no other mods is present. But it works good when using shift

**Comment by nimbXnumb** [comment]
> this with the latest version?

It doesn't work at all now :р
I thinks bug's reason is that mod treats normal and double slabs as bottom ones
