### ISSUE TITLE
Custom fluids have a whitish texture in the cauldron

### ISSUE THREAD

**Issue by MrRedstoneToGo** [MehVahdJukaar/amendments#80]
If you put a fluid from a mod (example Create mod) into a cauldron, it always has the same white texture, as if the water texture gets a colour afterwards.

![2024-05-17_19 30 00](https://github.com/MehVahdJukaar/amendments/assets/163460667/2a55430a-4c38-48af-a1a5-215b33ad965e)

Instead, you could use the texture that is created when you put the liquid into a fluid tank (Create). Maybe this texture is mandatory for every mod that adds a fluid.

**Comment by MehVahdJukaar** [comment]
version? does this happen with all modded liquids?

**Comment by MrRedstoneToGo** [comment]
I just tried it on Forge and the chocolate worked, so it's just a fabric problem. I also tested it on Create: Garnished and Modern Industrialization and both had problems with the cauldron. So it seems to be a general problem with the Fabric (1.20.1) version.

**Comment by MehVahdJukaar** [comment]
hm could you try downgrading moonlight lib 3 versions or so?

**Comment by MrRedstoneToGo** [comment]
I saw that you updated Moonlight Lib. Now the texture works again. As a small side effect, the honey texture has become lighter, since the texture is no longer taken from Amendments, but from Create. I actually don't think that's so bad.

Many thanks for that! You're doing a really good job!

**Comment by MehVahdJukaar** [comment]
yeah thats intented. they take textures from mods that add those fluids if they are there
