### ISSUE TITLE
Issue 1.20.1 crashing server/client when pulling a torch into inv

### ISSUE THREAD

**Issue by hi4444** [MehVahdJukaar/amendments#88]
[crash-2024-06-11_11.33.52-client.txt](https://github.com/user-attachments/files/15791549/crash-2024-06-11_11.33.52-client.txt)

**Comment by MehVahdJukaar** [comment]
are you sure you have latest moonlight version? check your mods are updated

**Comment by hi4444** [comment]
will try updating it again
