### ISSUE TITLE
Crash - Terrafirmacraft incompatibility?

### ISSUE THREAD

**Issue by SheReyy** [MehVahdJukaar/amendments#90]
MC: 1.20.1
Forge: 47.2.6
Amendments: 1.20-1.2.4

What happened? 
I tried to hold a torch from Terrafirmacraft. The game just crashed after I had it in my main hand for 1 second.

[Here](https://gist.github.com/IamRyan30/b1cb4ec6d2ad9b885b9c5845eca1f77a)'s the crash and [here](https://gist.github.com/IamRyan30/225e72371aec4b5d17397f3edfa4a903)'s the log.

**Comment by IamRyan30** [comment]
Update: it wasn't a TFC torch. It was actually a vanilla torch. I don't know if this is related to TFC anymore

**Comment by MehVahdJukaar** [comment]
update moonlight lib

**Comment by IamRyan30** [comment]
Fixed. Sorry for the trouble
