### ISSUE TITLE
Craft Tweaker / Amendments Crash with Cauldrons

### ISSUE THREAD

**Issue by Lonemind** [MehVahdJukaar/amendments#91]
Minecraft 1.20.1
Amendments 1.2.4
Moonlight 2.11.41
Supplementaries 2.8.15
CraftTweakrer 14.0.40

If there are scripts in the Scripts folder for Craft Tweaker and you toss items into a cauldron Minecraft crashes with this [crashlog](https://mclo.gs/cSZJLja).

The latter crashlog was generated with nothing but the aforementioned mods installed. It didn't point at any suspected mods but in my full modpack I get this [crashlog](https://mclo.gs/JGCavi7) that points to Amendments and CraftTweaker as the suspected mods. (And Recipe Essentials but I get the crash even when removing that mod).

I'm posting this issue both on the Amendments Github and CraftTweaker. I'll edit each post to crosslink the issues.

Edit: https://github.com/CraftTweaker/CraftTweaker/issues/1741
Script used as a test. https://mclo.gs/ISMc8Rw
I am using Forge 47.3.1

**Comment by MehVahdJukaar** [comment]
this was fixed
