### ISSUE TITLE
Collecting water from dyed cauldrons crashes the game.

### ISSUE THREAD

**Issue by UshankThePog** [MehVahdJukaar/amendments#92]
Right clicking a cauldron containing dyed water with a bucket causes the game to crash.

**Comment by MrRedstoneToGo** [comment]
Not only when a bucket is filled, but generally when you right-click on a Liquid Cauldron, but it cannot be filled/emptied.

**Comment by MrRedstoneToGo** [comment]
Then close it, I can't do that.
