### ISSUE TITLE
Slime cauldrons are completely busted

### ISSUE THREAD

**Issue by Fingernailsss** [MehVahdJukaar/amendments#93]
First of all, when right clicking a slime cauldron with a slimeball, the game crashes. this was not present in previous versions. no, the outcome was completely different, but still very broken. In older versions, right clicking a lime cauldron with a slimeball would cause a slime block to pop out. just by sitting there, filling the cauldron with slime, you could DUPE SLIMEBALLS. Infinitely. Forever.

Please fix.

**Comment by MehVahdJukaar** [comment]
can you elaborate on that? I cant replicate nothing of this. putting slimeballs in cauldrons work fine, same for putting slimeballs in it. Are all your mods updated?

**Comment by Fingernailsss** [comment]
You have to right click a filled slime cauldron with a slimeball.

**Comment by Fingernailsss** [comment]
[https://pastebin.com/1EJd9aEP](url)

Crash Log

**Comment by MehVahdJukaar** [comment]
Use new version

**Comment by Fingernailsss** [comment]
Crash: fixed

but the dupe somehow got worse, now you get 4 slime blocks from just filling a cauldron with slime

1. it take 4 slimeballs to fill a cauldron.

2. clicking it with another slimeball gives you 4 slime blocks

3.  those uncraft into 36 slimeballs

4. infinite dupe

**Comment by MehVahdJukaar** [comment]
hmm i forge or fabric?

**Comment by Fingernailsss** [comment]
forge

**Comment by Fingernailsss** [comment]
Good news! whatever you did fixed the dupe.

Bad new. now a slimeball just appears in my offhand when performing the method.

**Comment by MehVahdJukaar** [comment]
thats intended. you are taking it out with your offhand
