### ISSUE TITLE
Crash when holding a Torch 1.20.1-1.2.8

### ISSUE THREAD

**Issue by Cortekk** [MehVahdJukaar/amendments#95]
Game is crashing, when i hold a torch in my hand (includes modded torches too).

The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: class net.mehvahdjukaar.amendments.client.renderers.TorchRendererExtension tried to access private method 'void net.minecraft.client.renderer.ItemInHandRenderer.m_109382_(com.mojang.blaze3d.vertex.PoseStack, net.minecraft.world.entity.HumanoidArm, float)' (net.mehvahdjukaar.amendments.client.renderers.TorchRendererExtension is in module amendments@1.20-1.2.8 of loader 'TRANSFORMER' @24fc2c80; net.minecraft.client.renderer.ItemInHandRenderer is in module minecraft@1.20.1 of loader 'TRANSFORMER' @24fc2c80)

**Comment by MehVahdJukaar** [comment]
are you sure your mods are updated?

**Comment by Cortekk** [comment]
i think they are, tried a diffrent dynamic light mod, Ryo... still crashes. i can play with 1.2.3, no crashes. Tried multiple versions, till 1.2.3 with 1.2.4 and upwards the game crashed.

**Comment by MehVahdJukaar** [comment]
just update your mods

**Comment by Cortekk** [comment]
Jup, it was my old Moonlight lib 2.11.31 was outdated, with the newest it works flawless, thanks.
