### ISSUE TITLE
Supplementaries copper lanterns don't extinguish when placed on the wall in the Aether

### ISSUE THREAD

**Issue by TyrionReyukra** [MehVahdJukaar/amendments#96]
When placing a Copper Lantern from Supplementaries in the Aether, it will only extinguish when placed on the ground or ceiling.
Placing it on the wall using the Amendments wall lanterns causes it to bypass the effect.
The wall lantern can still be extinguished manually via right click
![2024-06-26_21 34 33](https://github.com/MehVahdJukaar/amendments/assets/83680313/7273aac3-21da-4264-8b50-8918b000439e)

**Comment by TyrionReyukra** [comment]
The lanterns work as intended in the overworld. Being able to manually be extinguished and ignited.

https://github.com/MehVahdJukaar/amendments/assets/83680313/526226d9-2f66-45c6-a8b0-162c01900241

The Aether will automatically extinguish blocks like the campfire (and with the official enhanced extinguishing addon, torches and lanterns) and prevents re-lighting them via flint and steel and fire charges as fire creation methods aren't allowed in the dimension (with the exception of the fireballs from the Sun Spirit fight and "soul fire" items)

Supplementaries seems to have built in compatibility with the Aethers extinguishing mechanic, as shown in the attached screenshot with the Aethers "Placement Conversion" recipe system.

![2024-06-27_11 31 42](https://github.com/MehVahdJukaar/amendments/assets/83680313/39304d79-0641-48a9-b2d5-58609c490751)

I hope I showcased the issue well enough in the attached video.

https://github.com/MehVahdJukaar/amendments/assets/83680313/6b667d02-1243-4825-aea8-c599934b93e6

When in the Aether, they extinguish as intended when on the floor or ceiling, but bypass the Aethers automatic extinguishing effect when on the wall.
I believe the Amendments wall variation doesn't have a "recipe" for the Aethers "Placement Conversion" system.

**Comment by MehVahdJukaar** [comment]
I don't have any code whatsoever for the aether. Maybe they have something and it's not working. In that case it's their issue. Even if they don't have something they clearly are messing with lit blocks so it's still something that should be adde dby then

**Comment by TyrionReyukra** [comment]
Ah, yup. I just looked through the stuff in the Aether .jar, and there's a placement conversion recipe for the Supplementaries copper lantern in it.

I was convinced that mod compatibility was handled on the Supplementaries/Amendments side, not the Aether's side, my bad.
I'll see if I can make my own datapack fix, and report it to the Aether github asap.
